### ISSUE TITLE
Issues loading @undecaf/zbar-wasm

### ISSUE THREAD

**Issue by Firefox2005** [undecaf/barcode-detector-polyfill#1]
First of all thanks for your work - seems to be a well performing barcode scanning solution. 
I'm using npm to install it in an Angular/TypeScript project. But compilation fails because it can't resolve the CDN import of @undecaf/zbar-wasm.

It seems like this way of importing is not supported by the version I'm using.
Any help on how to properly load the library at runtime with the provided npm package would be appreciated.

**Comment by undecaf** [comment]
I assume that Webpack is used for bundling your Angular app. Since I do not use Webpack much, I can only give general advice.

The polyfill package contains an `import` statement for zbar-wasm similar to `import {...} from "https://cdn.jsdelivr.net/npm/@undecaf/zbar-wasm@0.9.10/dist/main.js"`. When bundling your app, this statement must be transferred to your bundle unmodified by the bundler. At runtime, the browser will fetch zbar-wasm from this location. Usually the bundler will try to resolve the `import` target to a module that will be bundled -- in this special case, we do not want zbar-wasm to be resolved and bundled!

The strategy that I use e.g. for Rollup and esbuild is to declare the CDN link (`"https://cdn.jsdelivr.net/npm/@undecaf/zbar-wasm@0.9.10/dist/main.js"`) as an external reference in the build configuration so that the bundler does not attempt to resolve it. The [polyfill example directory](https://github.com/undecaf/barcode-detector-polyfill/tree/master/example) contains build files for Rollup (`rollup.config.js`) and esbuild (`esbuild.config.js`) demonstrating how to achieve this. The same strategy should be applied to Webpack.

I hope this helps a little.

**Comment by Firefox2005** [comment]
Thank you! I figured it out eventually. If someone ever stumbles upon that as well, I used the following webpack configuration:

```
{
     target: "es2020",
     externalsPresets: { web: false, webAsync: true },
     externals: /^("https:\/\/cdn\.jsdelivr\.net\/npm\/@undecaf\/zbar-wasm@0\.9\.10\/dist\/main\.js")/i,
     experiments: {
        outputModule: true,
     },
     output: {
        module: true,
     },
     externalsType: "module",
}
```

**Comment by urielaero** [comment]
Thanks to the information in this Issue I was able to find the cause of a similar problem and I leave here my solution in case someone needs it in the future. In my case it was for webpack 4 and webpacker (RoR project).

Add `scripts`:
```html
  ...
  <script src="https://cdn.jsdelivr.net/npm/@undecaf/zbar-wasm/dist/index.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@undecaf/barcode-detector-polyfill/dist/index.js"></script>
```
Add `externals`: (In my case `config/webpack/environment.js`)
```rb
...
environment.config.externals = /barcode-detector-polyfill|zbar-wasm/
```

Thank you very much for the tool it worked perfect for me.
