### ISSUE TITLE
Scanner goes infinitely / doesn't stop after reading a barcode

### ISSUE THREAD

**Issue by abdulwahabalm** [undecaf/barcode-detector-polyfill#10]
The scanner is really good and is of high quality but it doesn't stop even after it detects a barcode.

can there be a way for the scanner to stop after scanning a barcode ?

**Comment by undecaf** [comment]
Could you please provide a minimal working example that demonstrates this behavior?

I am asking this because the polyfill does not behave like that in the unit tests and in the examples.

**Comment by abdulwahabalm** [comment]
I attempted to write a minimal working example of you code  and it didn't really work

but my attempt was that 

function detect(source){
 return detector
.detect(source)
.then(symbols => {

/* 
rest of code 
*/

detectVideo(false) 
// my assumption is it would have worked the same way the camera disappears when you trigger detectImg

})

**Comment by undecaf** [comment]
I assume that you are referring to the code in `barcode-detector-polyfill/example-bundled/main.js`

In order to stop scanning as soon as a symbol has been detected, I would suggest to do something like this:

```javascript
function detect(source) {
    return detector
        .detect(source)
        .then(symbols => {
           // ...
           // Add this after the code block:
           if (symbols.length > 0) {
               detectVideo(false)
           }
        })
}
```

To start scanning the video that is playing in the `<video>` element, call `detectVideo()` without arguments (as in the `videoBtn` click listener) . This will clear the previous bounding box.

**Comment by abdulwahabalm** [comment]
Thank you! it worked
