### ISSUE TITLE
zbar-wasm@0.9.14 error

### ISSUE THREAD

**Issue by gassssty** [undecaf/barcode-detector-polyfill#11]
Hi guys!

I am trying to use this plugin in Angular 12 but I have this error:
external "https://cdn.jsdelivr.net/npm/@undecaf/zbar-wasm@0.9.14/dist/main.js" - Error: The target environment doesn't support dynamic import() syntax so it's not possible to use external type 'module' within a script

I am trying to solve this and read the 8 closed issues but I am not getting the correct answer.

Any help please?

**Comment by gassssty** [comment]
I installed that with npm and put it in index.html but it doesn't work.

**Comment by undecaf** [comment]
In order to be able to handle issues more systematically, I have added a form for bug reporting. I kindly ask you to provide details about this issue as detailed below:

**To Reproduce**

A minimal working example that reproduces the behavior would be much appreciated.

Or else the environment in which the behavior occurs needs to be specified:
 - Which JavaScript environment (Node/browser/other)?
 - Which framework(s)?
 - Which devtools, including their configuration files?
 - `package.json` content
 - Any other context about the problem

**Comment by gassssty** [comment]
Hi! I am just puting the import
![image](https://github.com/undecaf/barcode-detector-polyfill/assets/83598997/8abd273e-155e-41e2-b342-780cc2676250)

And then, this part in the code:
![image](https://github.com/undecaf/barcode-detector-polyfill/assets/83598997/96baddd2-0524-4075-923c-6be1c60aa59d)

I am trying to use it in browser app but it brokes when I compile the project. The red rectangle that I show you, if I don't put it or just comment that, the project compiles perfect. 

What I use is Ionic 5.34.

Package.json content:
![image](https://github.com/undecaf/barcode-detector-polyfill/assets/83598997/da3bc04f-480b-4c07-b0b4-847d25916090)

That's it. Just that. I hope I can solve this because is very urgent.

Thanks!!

**Comment by gassssty** [comment]
And... to compile, I am using: ionic cap copy android

**Comment by gassssty** [comment]
And more info, when I try to compile with ionic cap copy android:

external "https://cdn.jsdelivr.net/npm/@undecaf/zbar-wasm@0.9.14/dist/main.js" - Error: The target environment doesn't support dynamic import() syntax so it's not possible to use external type 'module' within a script

[ERROR] An error occurred while running subprocess ng.

        ng.cmd run app:build exited with exit code 1.

        Re-running this command with the --verbose flag may provide more information.

(Image) ->
![image](https://github.com/undecaf/barcode-detector-polyfill/assets/83598997/8529f36b-b154-4043-968b-be5bea58486f)

**Comment by undecaf** [comment]
As I am not familiar with Iconic and the Angular build process, I can only give general advice here.

I suggest to bundle `zbar-wasm` with your app (instead of trying to load it at runtime) as [explained here](https://github.com/undecaf/barcode-detector-polyfill#bundling-dependency-undecafzbar-wasm).

The important points with bundling are:

1. Have your bundler replace `'https://cdn.jsdelivr.net/npm/@undecaf/zbar-wasm@0.9.14/dist/main.js'` with `'@undecaf/zbar-wasm'` in the bundles. [This config file](https://github.com/undecaf/barcode-detector-polyfill/blob/master/example-bundled/rollup.config.js) demonstrates this for [Rollup](https://rollupjs.org/) and [this one](https://github.com/undecaf/barcode-detector-polyfill/blob/master/example-bundled/esbuild.config.js) for [esbuild](https://esbuild.github.io/). Other bundlers will require equivalent configurations. 

1. Let your bundler copy the file `zbar.wasm` to the _same path_ as the bundle that contains the rest of `@undecaf/zbar-wasm`. This is also shown in the config files mentioned above.

**Comment by gassssty** [comment]
Okay thanks, I will try this. How do I get the zbar.wasm file? Or, where is located?

**Comment by undecaf** [comment]
It is part of the package `@undecaf/zbar-wasm` in `node_modules`.

**Comment by undecaf** [comment]
Closing this issue as it has been inactive for more than 4 weeks.
